version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: stm
      POSTGRES_USER: stm
      POSTGRES_PASSWORD: stm
    volumes:
      - stm-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stm -d stm"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stm:stm@db:5432/stm?schema=public
      JWT_SECRET: change_me_in_prod
      PORT: 3000
      ORIGIN: http://zeit.dacrode.de
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env:ro

volumes:
  stm-db:
    name: stm-db
